version: '3.8'

services:
  api:
    container_name: wefit_api
    image: joaodicous/desafio-wefit:latest
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://db:5432/wefit
      DB_USERNAME: admin
      DB_PASSWORD: admin
    depends_on:
      - db
  db:
    container_name: 'wefit_db'
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: wefit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin