spring.application.name=wefit
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto: none
spring.jpa.show-sql: true
spring.jpa.format-sql: true
spring.datasource.url: ${DB_URL:jdbc:postgresql://localhost:5432/wefit}
spring.datasource.username: ${DB_USERNAME:admin}
spring.datasource.password: ${DB_PASSWORD:admin}
spring.datasource.database-platform: org.hibernate.dialect.PostgreSQL9Dialect