CREATE TABLE PESSOA(
    ID BIGSERIAL,
    DATA_HORA_CADASTRO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    TIPO_PESSOA VARCHAR(255) NOT NULL,
    CNPJ VARCHAR(14),
    CPF VARCHAR(11),
    EMAIL VARCHAR(255),
    NOME VARCHAR(255),
    CELULAR VARCHAR(11),
    TELEFONE VARCHAR(11),

--    ENDERECO
    CEP VARCHAR(8),
    LOGRADOURO VARCHAR(255),
    NUMERO VARCHAR(255),
    COMPLEMENTO VARCHAR(255),
    CIDADE VARCHAR(255),
    BAIRRO VARCHAR(255),
    ESTADO VARCHAR(255),

    PRIMARY KEY(ID)
);